name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the information below.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New MCP tool (maps to existing Google API)
        - Enhancement to existing tool
        - New Google API support
        - Documentation improvement
        - Developer experience improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: affected-api
    attributes:
      label: Target API
      description: Which Google API would this feature use?
      options:
        - Google Docs API
        - Google Sheets API
        - Google Slides API
        - Google Drive API
        - Multiple APIs
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Currently, there's no way to...
        This makes it difficult to...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        Add a new tool called `docs_foo` that...
        Or enhance `docs_get` to support...
    validations:
      required: true

  - type: textarea
    id: google-api-reference
    attributes:
      label: Google API Reference
      description: |
        If this maps to a specific Google API method, provide the reference link.
        Example: https://developers.google.com/docs/api/reference/rest/v1/documents/get
      placeholder: "https://developers.google.com/..."

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case for this feature
      placeholder: |
        I want to be able to...
        This would help me...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: |
        I tried using tool X, but...
        Current workaround is...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my use case
        - High - Significantly improves my workflow
        - Medium - Nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: "Add any other context about the feature request here"

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with 1:1 API mapping design principles
          required: false
        - label: I have provided a clear use case
          required: true
